### ISSUE TITLE
Media/Contact/Gallery details

### ISSUE THREAD

**Issue by gabrielavbarrios** [gabrielavbarrios/gabrielavbarrios.github.io#2]
**In the media page:**
The "Acting Reel" title needs to be in Helvetica, (font-size: 2rem;) (font-width: 300). 

**In the contact page:**
It needs to have a grey background. Color: #e0e0e0

**In the Gallery > Production Stills/BTS:**
I want only this section to have captions, in thin Helvetica.

**In "Gabriela Barrios" title:**
Change this for a bold serif font. I tried to do it and it doesn't change. Something like Baskerville, or something like this:
![text-1726173727249](https://github.com/user-attachments/assets/afbc2096-ed43-4ab0-8dd0-81632a8099b2)

You could actually try to use that same thing. The html that the page gave me was this:
<a href="https://www.fontspace.com/category/bold"><img src="https://see.fontimg.com/api/rf5/JR5q7/MTU4YjJkZmYwZTY2NDRjYmFkYTRkMGJjMGM3MGI0NDMudHRm/R2FicmllbGEgQmFycmlvcw/sandana-regular.png?r=fs&h=134&w=2000&fg=000000&bg=FFFFFF&tb=1&s=67" alt="Bold fonts"></a>

**Comment by jmichuda** [comment]
Changed to Baskerville
